Allow importing Jersey AbstractBinder
airlift/airbase pull request #365
Opened 2023-06-08 21:49 UTC by wendigo

2023-06-08 23:39 UTC, electrum commented
Can you update CHANGES?

2023-06-09 07:12 UTC, Randgalt approved these changes

2023-06-09 07:17 UTC, Randgalt requested changes
I found other references in Galaxy:

```
import org.glassfish.jersey.internal.MapPropertiesDelegate;
```

2023-06-09 10:12 UTC, Randgalt approved these changes

2023-06-10 08:56 UTC, wendigo commented
PTAL @electrum

2023-06-10 08:58 UTC, Randgalt approved these changes

2023-06-12 01:46 UTC, electrum approved these changes

2023-06-12 01:46 UTC, merged